# Generated by Django 4.2.7 on 2024-02-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitopx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
