# Generated by Django 4.2.7 on 2024-01-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitopx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='escuderia',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
