# Generated by Django 4.2.7 on 2024-02-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitopx', '0002_alter_circuito_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
