# Generated by Django 4.2.9 on 2024-01-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitopx', '0002_alter_carrera_puntos_alter_escuderia_puntos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuderia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logos/'),
        ),
    ]
