# Generated by Django 4.2.7 on 2024-02-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitopx', '0003_alter_circuito_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
