# Generated by Django 4.2.7 on 2024-02-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitopx', '0005_liga'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales', models.IntegerField(default=0)),
                ('valor', models.IntegerField(default=0)),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitopx.piloto')),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_jornada', models.IntegerField(default=0)),
                ('adelantamiento', models.IntegerField(default=0)),
                ('estado', models.CharField(blank=True, choices=[('DSQ', 'DSQ'), ('DNF', 'DNF')], max_length=3, null=True)),
                ('q2', models.BooleanField(default=False)),
                ('q3', models.BooleanField(default=False)),
                ('vuelta_rapida', models.BooleanField(default=False)),
                ('amonestacion', models.IntegerField(default=0)),
                ('sancion3', models.IntegerField(default=0)),
                ('sancion5', models.IntegerField(default=0)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitopx.circuito')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitopx.pilotojuego')),
            ],
        ),
    ]
