# Generated by Django 4.2.7 on 2024-02-09 18:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitopx', '0006_pilotojuego_jornada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.IntegerField(default=1500000)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('puesto', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitopx.liga')),
                ('piloto', models.ManyToManyField(to='mundialitopx.pilotojuego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
