# Generated by Django 4.2.7 on 2024-02-04 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitopx', '0007_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='circuito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mundialitopx.circuito'),
        ),
    ]
