# Generated by Django 4.2.10 on 2024-02-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitopx', '0007_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='escuderia',
            field=models.ManyToManyField(blank=True, null=True, to='mundialitopx.escuderia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='piloto',
            field=models.ManyToManyField(blank=True, null=True, to='mundialitopx.piloto'),
        ),
    ]
